version: '3.3'

services:
   db:
     image: philipz/k8s-mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always

   wordpress:
     depends_on:
       - db
     image: philipz/k8s-wordpress:latest
     ports:
       - "80:80"
     restart: always
volumes:
    db_data:
