version: '3.3'

services:
   db:
     image: philipz/k8s-mysql:5.7
     restart: always

   wordpress:
     depends_on:
       - db
     image: philipz/k8s-wordpress:latest
     ports:
       - "80:80"
     restart: always
     deploy:
       replicas: 2

